-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  rbac_repositories
CREATE TABLE IF NOT EXISTS rbac_repositories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  url  VARCHAR(1024) NULL,
  signing_key_id BIGINT NULL,                      -- optional: verify snapshot signatures
  status TEXT NOT NULL DEFAULT 'active',           -- 'active','disabled'
  last_synced_at TIMESTAMPTZ(6) NULL,
  last_commit VARCHAR(128) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
